# Generated by Django 2.0.2 on 2018-09-25 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookstore', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='year',
            field=models.IntegerField(default=1990),
            preserve_default=False,
        ),
    ]
