# Generated by Django 2.0.2 on 2018-09-25 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookstore', '0003_auto_20180925_1744'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='year',
        ),
        migrations.AddField(
            model_name='book',
            name='publish_date',
            field=models.DateField(default='2018-09-25'),
        ),
    ]
