# Generated by Django 2.0.2 on 2018-09-28 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookstore', '0005_auto_20180928_1116'),
    ]

    operations = [
        migrations.AddField(
            model_name='requests',
            name='get',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='requests',
            name='post',
            field=models.TextField(blank=True, null=True),
        ),
    ]
