# Generated by Django 2.0.2 on 2018-09-28 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookstore', '0006_auto_20180928_1118'),
    ]

    operations = [
        migrations.AddField(
            model_name='requests',
            name='status_code',
            field=models.CharField(default=200, max_length=50),
        ),
    ]
