# Generated by Django 2.0.2 on 2018-09-28 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookstore', '0007_requests_status_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requests',
            name='status_code',
            field=models.CharField(max_length=50),
        ),
    ]
