# Generated by Django 2.0.2 on 2018-09-28 13:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookstore', '0008_auto_20180928_1157'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='requests',
            name='get',
        ),
    ]
