# Generated by Django 2.0.2 on 2018-10-02 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookstore', '0009_remove_requests_get'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='requests',
            name='status_code',
        ),
        migrations.AlterField(
            model_name='book',
            name='publish_date',
            field=models.DateField(default='2018-10-02'),
        ),
    ]
